apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Values.namespace }}-keycloak
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - keycloak.{{ .Values.namespace }}.global
  ports:
  - number: 80
    name: keycloak
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: {{ .Values.keycloak_ip }}
